# Generated by Django 4.1.1 on 2022-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('expiry_time', models.DateTimeField()),
                ('hash', models.CharField(max_length=7)),
                ('full_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['hash'], name='hash_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['full_url'], name='full_url_idx'),
        ),
    ]
