# Generated by Django 4.1.1 on 2022-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='hash',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
