import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [isURLValid, setIsURLValid] = useState(false)

  return (
    <div className="p-0 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto self-center p-4 min-h-screen flex">
        <div className='m-auto w-full flex flex-col items-center gap-12'>
          <h1 className="md:text-5xl text-4xl font-bold text-gray-800 text-center">
            OmniHR URL Shortener
          </h1>

          <div className="flex flex-col w-full md:w-1/3 items-center gap-5 rounded-lg border border-gray-200 shadow-sm p-5">
            <input
              type="text"
              className="textinput"
              placeholder="https://google.com" required />
            <button className="btn btn-blue">Shorten!</button>
          </div>
        </div>

      </main>

      <footer className="m-auto text-center p-4 underline">
        Made by <a href='https://github.com/adylanrff'>Adylan Roaffa</a>
      </footer>
    </div>
  )
}

export default Home
